### ISSUE TITLE
Adding GitHub Actions and templates for BootBlox

### ISSUE THREAD

**Issue by iamrajiv** [VaibhavSaini19/BootBlox#15]
Adding ESLint and Prettier GitHub Action and PR and Issue templates to BootBlox will enhance the workflow of the repository.

ESLint:
ESLint is a static code analysis tool for identifying problematic patterns found in JavaScript code:

Prettier:
Prettier is an opinionated code formatter. It enforces a consistent style by parsing your code and re-printing it with its own rules that take the maximum line length into account, wrapping code when necessary.

**Comment by iamrajiv** [comment]
@VaibhavSaini19 I would like to work on this.

**Comment by VaibhavSaini19** [comment]
@iamrajiv sure. I am assigning this to you.

**Comment by t0xic0der** [comment]
Hi @iamrajiv, we are considering having a discussion regarding the feasibility and the viability of adding these to the project and considering how it could benefit the project. You are requested to use this ticket to mention those as the other contributors would join in for the discussions.

**Comment by iamrajiv** [comment]
@t0xic0der @VaibhavSaini19 
With issue and pull request templates, you can customize and standardize the information you'd like contributors to include when they open issues and pull requests in your repository.

ESLint is a static code analysis tool for identifying problematic patterns found in JavaScript code:

- You will find bugs and errors before they happen.
- You will spend less time testing new features.
- Your code (and your team's code) will be more consistent.

Prettier is a very popular code formatter which uses very opinionated but sensible styles to format your code and prevent the ongoing debates about code styles.

**Comment by t0xic0der** [comment]
> Adding GitHub Actions and templates for BootBlox

> With issue and pull request templates, you can customize and standardize the information you'd like contributors to include when they open issues and pull requests in your repository.

The issue title that you wrote could use some clarity. Now that you specify in your comment here, we get to know that you are talking about the issue and pull request templates.

**Comment by iamrajiv** [comment]
@t0xic0der Yeah and I am also talking of adding  ESLint and Prettier too. They will automatically refactor and format the code in a more readable way whenever there is push and pull requests.

Reference:
https://eslint.org/
https://prettier.io/

**Comment by iamrajiv** [comment]
@VaibhavSaini19 @t0xic0der any updates on this

**Comment by VaibhavSaini19** [comment]
@iamrajiv  Sounds good to me

**Comment by VaibhavSaini19** [comment]
@iamrajiv The Format action is currently applying prettier to all the files. We would like to apply it only to specific files and ignore the rest (like node_modules and some other css files). Can you do that please? I think we might need to roll back your commit?
Following files and folders are to be ignored:
- `assests`
- `css`
- `extras`
- `js/highlight`
- `node_modules`

Also, following options need to be used for prettier:
- use `spaces` for indentation
- use `4` spaces as indentation

It would be great if you could create a `.prettierignore` for ignoring the mentioned files and a `.prettierrc.json` config file for prettier for the above options.

**Comment by VaibhavSaini19** [comment]
@iamrajiv I need your help urgently, can I contact you personally?
