### ISSUE TITLE
SVG thumbnails for "Blog" category

### ISSUE THREAD

**Issue by VaibhavSaini19** [VaibhavSaini19/BootBlox#17]
## 🚀 Feature

A default thumbnail is being used currently for a code block.
For the "Blog" category, SVG thubmnails that represents the code block preview in an abstract manner (like a skeleton template) would help a user to get an intuition about the template in a glance in the sidebar itself

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would enhance the user experience by providing a quick abstract preview of the code block in the sidebar that would reduce the time required to find the desired template. The thumbnail can be designed using any designing tool like Figma, Adobe XD etc.

**Comment by s-katte** [comment]
Hey @VaibhavSaini19, I would like to work on this issue. 
Please assign me this.

**Comment by VaibhavSaini19** [comment]
Sure. Happy hacking 😀
