### ISSUE TITLE
SVG thumbnails for "Feature" category

### ISSUE THREAD

**Issue by VaibhavSaini19** [VaibhavSaini19/BootBlox#19]
## 🚀 Feature

A default thumbnail is being used currently for a code block.
For the **"Feature"** category, SVG thubmnails that represents the code block preview in an abstract manner (like a skeleton template) would help a user to get an intuition about the template in a glance in the sidebar itself

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would enhance the user experience by providing a quick abstract preview of the code block in the sidebar that would reduce the time required to find the desired template. The thumbnail can be designed using any designing tool like Figma, Adobe XD etc.

**Comment by erinknight242** [comment]
I'll take this one

**Comment by t0xic0der** [comment]
@erinknight242 Please take a look at [this](https://github.com/VaibhavSaini19/BootBlox/issues/22#issuecomment-709885679).

**Comment by erinknight242** [comment]
@VaibhavSaini19 may I have this one?

**Comment by erinknight242** [comment]
@VaibhavSaini19 may I have this one?

**Comment by erinknight242** [comment]
@VaibhavSaini19 Can I have this one next?

**Comment by VaibhavSaini19** [comment]
Sure @erinknight242
