### ISSUE TITLE
SVG thumbnails for "Gallery" category

### ISSUE THREAD

**Issue by VaibhavSaini19** [VaibhavSaini19/BootBlox#21]
## 🚀 Feature

A default thumbnail is being used currently for a code block.
For the **"Gallery"** category, SVG thubmnails that represents the code block preview in an abstract manner (like a skeleton template) would help a user to get an intuition about the template in a glance in the sidebar itself

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would enhance the user experience by providing a quick abstract preview of the code block in the sidebar that would reduce the time required to find the desired template. The thumbnail can be designed using any designing tool like Figma, Adobe XD etc.

**Comment by erinknight242** [comment]
I'll take this one

**Comment by t0xic0der** [comment]
@erinknight242 Please take a look at [this](https://github.com/VaibhavSaini19/BootBlox/issues/22#issuecomment-709885679).

**Comment by erinknight242** [comment]
@VaibhavSaini19 may I have this one?

**Comment by VaibhavSaini19** [comment]
@erinknight242 you can work on the issues one by one. Please let me know which one you would like to be assigned for now, so that others can take up the other issues. When you are done with one, and other issues have not been assigned to someone else yet, we can assign that to you

**Comment by t0xic0der** [comment]
> @erinknight242 you can work on the issues one by one. Please let me know which one you would like to be assigned for now, so that others can take up the other issues. When you are done with one, and other issues have not been assigned to someone else yet, we can assign that to you

+1 on that @VaibhavSaini19. Assigning loads of issues to a single assignee might not be the wisest thing to do here.

**Comment by erinknight242** [comment]
Thanks @VaibhavSaini19, I understand. I am ready to work on these images now. If you wait to assign me the next one until the previous PR is merged, it will take multiple days to close them all out where I can just knock them out right now if they are marked for me. Feel free to assign as you prefer.

**Comment by VaibhavSaini19** [comment]
Cool, I'll assign you the next as soon as you are done with this one

**Comment by t0xic0der** [comment]
> Thanks @VaibhavSaini19, I understand. I am ready to work on these images now. If you wait to assign me the next one until the previous PR is merged, it will take multiple days to close them all out where I can just knock them out right now if they are marked for me. Of course as it's your project, feel free to assign as you prefer.

I understand that you mean well for the project @erinknight242 and we appreciate it. :smile: But we would want to give equal opportunity to everyone looking for candidate issues on `hacktoberfest`. Once you are done with one issue, we would certainly assign you with another.
