### ISSUE TITLE
SVG thumbnails for "Header" category

### ISSUE THREAD

**Issue by VaibhavSaini19** [VaibhavSaini19/BootBlox#22]
## 🚀 Feature

A default thumbnail is being used currently for a code block.
For the **"Header"** category, SVG thubmnails that represents the code block preview in an abstract manner (like a skeleton template) would help a user to get an intuition about the template in a glance in the sidebar itself

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would enhance the user experience by providing a quick abstract preview of the code block in the sidebar that would reduce the time required to find the desired template. The thumbnail can be designed using any designing tool like Figma, Adobe XD etc.

**Comment by erinknight242** [comment]
I'll take this one

**Comment by t0xic0der** [comment]
@erinknight242,

**Asking politely for an assignment would be appreciated.**

The maintainers of this repository spend countless hours into QAing the project and checking the stuffs which can be added so the least, the contributors can do is to ask for issue assignment politely and not state that you are taking it right away.

For your reference @VaibhavSaini19

**Comment by VaibhavSaini19** [comment]
Thanks @t0xic0der, I was a little busy with the actions. Everything is working fine now. 

@erinknight242 If you would like, I can assign this to you

**Comment by t0xic0der** [comment]
No worries @VaibhavSaini19.

Feel free to pick alternatives like CodeClimate, Travis CI or FOSSA, if "Actions" is too troubling.

**Comment by erinknight242** [comment]
@t0xic0der Hi, I'm sorry I didn't intend sound impolite. I was waiting for it to be assigned before completing the PR (or any of the other tickets that I requested.

**Comment by erinknight242** [comment]
@VaibhavSaini19 may I have this one?

**Comment by VaibhavSaini19** [comment]
Sure @erinknight242
