### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by s-katte** [VaibhavSaini19/BootBlox#25]
## 📚 Documentation

In the steps of CONTRIBUTING.md, the step for making a new branch is missing.
Also, dedicated steps for adding SVG thumbnails along with file naming conventions are missing.

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

**Comment by VaibhavSaini19** [comment]
Thanks @s-katte for noticing. I'll take care of this

**Comment by VaibhavSaini19** [comment]
The CONTRIBUTING.md have been updated, thanks
