### ISSUE TITLE
Display thumbnails dynamically

### ISSUE THREAD

**Issue by VaibhavSaini19** [VaibhavSaini19/BootBlox#35]
## 🚀 Feature

Currently, a temporary thumbnail is being used for all the code blocks by hard coding the source attribute of the image. This can be made dynamic, by checking if the corresponding thumbnail for the code block is available or not. If yes, then use that, otherwise use the temporary thumbnail.

## Have you spent some time to check if this issue has been raised before?

Yes. Similar issue doesn't exist

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would ensure that all the thumbnails added are displayed properly and the categories for which thumbnails have not been added yet, only those will have the temporary thumbnail

**Comment by erinknight242** [comment]
@VaibhavSaini19 may I have this one?

**Comment by erinknight242** [comment]
@VaibhavSaini19 can I have this one next? Would you like the dynamic replacement to assume that the image names follow the convention, or code the full image name for each like I did previously?

**Comment by VaibhavSaini19** [comment]
@erinknight242 yes, the thumbnails follow the name convention, so it needs to be checked if the corresponding thumbnail for a code block is present or not
