### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by VaibhavSaini19** [VaibhavSaini19/BootBlox#45]
## 📚 Documentation

Add code of conduct to maintain a healthy environment for the community

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

**Comment by s-katte** [comment]
Assign me this please @VaibhavSaini19.
