### ISSUE TITLE
Inconsistent thumbnails of Hero section

### ISSUE THREAD

**Issue by VaibhavSaini19** [VaibhavSaini19/BootBlox#53]
## 🚀 Feature

The thumbnails for the `Hero` section do not look consistent like the rest of the thumbnails

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/VaibhavSaini19/BootBlox/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

It would maintain consistent design across the project

**Comment by VaibhavSaini19** [comment]
@erinknight242 do you mind picking this up?

**Comment by erinknight242** [comment]
@VaibhavSaini19 Sure

**Comment by erinknight242** [comment]
@VaibhavSaini19 Do you want any redesign to the Hero thumbnail images themselves, other than making the line weights and dimensions more consistent with the others? Layout of them seems ok to me.

**Comment by VaibhavSaini19** [comment]
> other than making the line weights, colors, and dimensions more consistent with the others

That's it, nothing else. Layout is fine
