### ISSUE TITLE
Add code blocks for "Pricing Table" category

### ISSUE THREAD

**Issue by VaibhavSaini19** [VaibhavSaini19/BootBlox#6]
Code blocks / templates are required for listing pricing plans in the form of cards or tables. 
For example:
- https://dribbble.com/shots/5041388-WIP-Pricing-Comparison-Chart
- https://dribbble.com/shots/9392129-CometChat-Pro-Pricing
- https://dribbble.com/shots/14070207-Pricing-Section-01
- https://dribbble.com/shots/14070220-Pricing-Section-03
- https://dribbble.com/shots/14119952-Pricing-Exploration

Of course, these are just some references, you can come up with your own creative design. Just remember to use Bootstrap v5 as much as possible with minimal inline CSS

**Comment by pranavvp10** [comment]
Hi! can I work on this ? and can you give a more elaborate description of what you want in this issue @VaibhavSaini19

**Comment by t0xic0der** [comment]
Cool. @VaibhavSaini19 will assign you this issue as soon as he comes online. Be sure to get yourself registered at https://organize.mlh.io/participants/events/4659-hack-astrosonic, our official Hacktoberfest event to stay in touch with the fellow contributors of this project.

Also, feel free to leave a star on the project - should you find it worth your time. Happy hacking! :smile:

**Comment by VaibhavSaini19** [comment]
Hello @pranavvp10 . Thanks for your interest in this issue. I have update the description for more clarity. And as you requested, I am assigning this issue to you, so you can start to work on it.
Also, don't forget to register yourself at Hacktoberfeat, as mentioned by @t0xic0der to get a chance to win some goodies along the line. Let me know if you need anything else

**Comment by VaibhavSaini19** [comment]
@pranavvp10  You can visit the CONTRIBUTE.md (if you haven't already) to get started

**Comment by pranavvp10** [comment]
Thanks @VaibhavSaini19  for providing more info. I will start working on it. And also Thanks  @t0xic0der I will surely register.
